dell/azurestack-docs

layouts/partials/head-css.html, layouts/partials/hooks/body-end.html
A few sentences describing the overall goals of the pull request's commits.
| |
=> Change stylesheet loading logic to fix broken reference

config/_default/config.toml, config/development/config.toml, config/production/config.toml, layouts/partials/head-css.html, layouts/partials/hooks/body-end.html, layouts/partials/hooks/head-end.html
As per title. Tested locally with environment as close to prod as possible.
N/A
=> Remove BaseUrl and update refs

config/_default/config.toml, config/development/config.toml, config/production/config.toml, layouts/partials/head-css.html, layouts/partials/hooks/body-end.html, layouts/partials/hooks/head-end.html
=> Change baseURL in config

config/_default/config.toml, layouts/partials/hooks/body-end.html
Local testing is not representative of production environment.
Need to find a better way of doing this.
=> Revert BaseURL change

config/development/config.toml, layouts/partials/hooks/body-end.html
Search functionality will still be broken.
=> Re-enable canonifyURLs. Re-add main.js override

config/production/config.toml
Production config did not match development config.
=> Fix config disparity

.github/workflows/deploy.yml
Allow for dynamic buildURL on hugo build, so that the site can be built on a forked repo with a different GitHub pages URL.
N/A
=> Add dynamic baseURL on hugo build

content/en/docs/hub/SupportMatrix/2306/14G/_index.md, content/en/docs/hub/SupportMatrix/2309/14G/_index.md, content/en/docs/hub/SupportMatrix/2401/14G/_index.md
=> Remove references to EMC

content/en/docs/hci/SupportMatrix/2403/_index.md
Add warning regarding upgrade path from HCI 22H2 to 23H2
=> Add HCI 23H2 update warning

assets/scss/_styles_project.scss
Increase max width of main content and increase right margin to better align everything.
N/A
=> Change content width

content/en/docs/hci/SupportMatrix/Archive/WS2016/_index.md, content/en/docs/hci/SupportMatrix/Archive/_index.md
=> Add Firmware and Driver Matrix for Windows Server 2016

content/en/docs/hci/SupportMatrix/2406/14G-15G_HCI/_index.md
Add 23H2 update warning from the 2403 SM.
N/A
=> HCI 2406 - Add 23H2 update warning

content/en/docs/hci/StorageStack/01-Layers-Below-S2D-Stack/01-StorageDevices/_index.md
Replace with 'image' shortcode that fixes permalink (could do with renaming shortcode to something generic to avoid confusion).
| Fixes #95 |
=> Azure Stack HCI - Fix links to storage performance txt files

content/en/docs/hci/StorageStack/01-Layers-Below-S2D-Stack/01-StorageDevices/_index.md
Link changed location slightly.
| #95  |
=> Azure Stack HCI - Fix additional DellGEOS GitHub link

content/en/docs/hci/SupportMatrix/_index.md
=> Add SBE release notes to Support Matrix home page

content/en/docs/hci/SupportMatrix/2409/14G-15G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2412/14G-15G_HCI/_index.md
Remove unsupported message and add AX-640/AX-740xd to supported models.
N/A
=> Update 23H2 upgrade statement to include 14G systems

content/en/docs/hci/SupportMatrix/2409/14G-15G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2412/14G-15G_HCI/_index.md
=> 23H2 upgrade - Change from warning to note

content/en/docs/hci/BIOSandiDRAC/_index.md
=> Add AX-760, AX-4510c and AX-4520c to BIOS and iDRAC recommended config

config/development/config.toml, content/en/docs/hci/SupportMatrix/SBEReleaseNotes/_index.md, content/en/docs/hci/SupportMatrix/_index.md
Add note about 23H2 OS upgrade not supported by Dell on stretch clusters
N/A
=> Azure Local 23H2 stretch cluster note

content/en/docs/hub/PatchAndUpdate/16G/_index.md
=> Additional line breaks

.github/workflows/deploy.yml
The changes in Hugo 0.146.4 resolve the build issues with 0.146.X
=> Revert commit f07effc22ebb8f6f3709b87d94d23968a0906fb2

content/en/docs/hub/ReleaseNotes/2407/14G/_index.md, content/en/docs/hub/ReleaseNotes/2411/14G/_index.md, content/en/docs/hub/ReleaseNotes/2411/16G/_index.md, content/en/docs/hub/ReleaseNotes/2502/14G/_index.md, content/en/docs/hub/ReleaseNotes/2502/16G/_index.md
=> Remove Azure Stack Hub Tech Book links

README.md, config/_default/config.toml, content/en/_index.html, content/en/docs/_index.md, content/en/docs/hci/BIOSandiDRAC/_index.md, content/en/docs/hci/PlanningAzureStack/_index.md, content/en/docs/hci/SupportMatrix/2412/14G-15G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2412/16G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2412/_index.md, content/en/docs/hci/SupportMatrix/2503/14G-15G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2503/16G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2503/_index.md, content/en/docs/hci/SupportMatrix/Archive/WS2016/_index.md, content/en/docs/hci/SupportMatrix/Archive/_index.md, content/en/docs/hci/SupportMatrix/SBEReleaseNotes/_index.md, content/en/docs/hci/_index.md, content/en/docs/references/_index.md
As per title. For reference: https://learn.microsoft.com/en-us/azure/azure-local/rename-to-azure-local?view=azloc-2503
N/A
=> Rename Azure Stack HCI to Azure Local

content/en/docs/hci/SupportMatrix/2503/GoldenImages/_index.md
=> Add Azure Local Golden Images for 2503 release

content/en/docs/hci/SupportMatrix/_index.md
=> Add note about 24H2 OS upgrade/deployment

content/en/_index.html, content/en/docs/_index.md, content/en/docs/hci/SupportMatrix/2412/14G-15G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2503/14G-15G_HCI/_index.md, content/en/docs/hci/_index.md
Renaming “Dell AX Integrated System for Azure Local” to “Dell AX System for Azure Local”
N/A
=> Rename Integrated System to AX System for Azure Local

content/en/docs/hci/SupportMatrix/_index.md
=> Update note regarding stretched cluster 23H2 upgrades

content/en/docs/hci/SupportMatrix/_index.md
=> Fix stretch cluster note

content/en/docs/hci/SupportMatrix/2503/GoldenImages/_index.md
=> Update Azure Local Golden Images for 2503 release

content/en/docs/hci/SupportMatrix/2506/16G_HCI/_index.md, content/en/docs/hci/SupportMatrix/2506/_index.md
- RTS publication of Azure Local/HCI 2506 release for 16G platforms
| |
=> Add Azure Local 16G_HCI Support Matrix for 2506 release

content/en/docs/hci/SupportMatrix/2506/14G-15G_HCI/_index.md
As per note, the 2506 release for the AX-650, AX-750. AX-6515, AX-7525, AX-640, and AX-740xd platforms is coming soon.
N/A
=> Add Azure Local 14G-15G_HCI Support Matrix for 2506 release

content/en/docs/hci/SupportMatrix/2506/GoldenImages/_index.md
=> Update Azure Local Golden Images for 2506 release
